import { useEffect, useState } from "react";
import jsPDF from "jspdf";
import { getMonthlyReport } from "../services/reportService";
import "../styles/MonthlyReport.css";

function MonthlyReport() {
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    loadReport();
  }, []);

  const loadReport = async () => {
    try {
      const data = await getMonthlyReport();
      setReport(data.report);
    } catch (error) {
      console.log(error);
      alert("Unable to load monthly report.");
    } finally {
      setLoading(false);
    }
  };

  const downloadPDF = () => {
    if (!report) return;

    const doc = new jsPDF();

    doc.setFontSize(18);
    doc.text("Financial Habit Builder", 20, 20);

    doc.setFontSize(14);
    doc.text("Monthly Financial Report", 20, 35);

    let y = 55;

    doc.setFontSize(12);

    doc.text(`Total Income: ₹ ${report.totalIncome}`, 20, y);
    y += 10;

    doc.text(`Total Expense: ₹ ${report.totalExpense}`, 20, y);
    y += 10;

    doc.text(`Total Savings: ₹ ${report.totalSavings}`, 20, y);
    y += 10;

    doc.text(`Savings Rate: ${report.savingsRate}%`, 20, y);
    y += 10;

    doc.text(`Total Goals: ${report.totalGoals}`, 20, y);
    y += 10;

    doc.text(`Total Investments: ₹ ${report.totalInvestment}`, 20, y);
    y += 10;

    doc.text(`Total Habits: ${report.totalHabits}`, 20, y);
    y += 10;

    doc.text(`Completed Habits: ${report.completedHabits}`, 20, y);
    y += 20;

    doc.text("Generated by Financial Habit Builder", 20, y);

    doc.save("Monthly_Financial_Report.pdf");
  };

  if (loading) {
    return <h2 className="loading">Loading Report...</h2>;
  }

  return (
    <div className="report-page">
      <h1>Monthly Financial Report</h1>

      <div className="report-actions">
        <button className="pdf-btn" onClick={downloadPDF}>
          📄 Download PDF Report
        </button>
      </div>

      <div className="report-grid">
        <div className="report-card income">
          <h3>Total Income</h3>
          <h2>₹ {report.totalIncome}</h2>
        </div>

        <div className="report-card expense">
          <h3>Total Expense</h3>
          <h2>₹ {report.totalExpense}</h2>
        </div>

        <div className="report-card savings">
          <h3>Total Savings</h3>
          <h2>₹ {report.totalSavings}</h2>
        </div>

        <div className="report-card">
          <h3>Savings Rate</h3>
          <h2>{report.savingsRate}%</h2>
        </div>

        <div className="report-card">
          <h3>Total Goals</h3>
          <h2>{report.totalGoals}</h2>
        </div>

        <div className="report-card">
          <h3>Total Investments</h3>
          <h2>₹ {report.totalInvestment}</h2>
        </div>

        <div className="report-card">
          <h3>Total Habits</h3>
          <h2>{report.totalHabits}</h2>
        </div>

        <div className="report-card">
          <h3>Completed Habits</h3>
          <h2>{report.completedHabits}</h2>
        </div>
      </div>
    </div>
  );
}

export default MonthlyReport;
